version: '3.8'
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: /frontend/Dockerfile
      args:
        NODE_VERSION: 18.17.1
      cache_from:
        - frontend:latest
    volumes:
      - ./frontend:/app
      - /app/node_modules:/app/node_modules
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm start
    stdin_open: true
    tty: true
    networks:
      - steamate-network
  nginx:
    build:
      context: ./nginx
      dockerfile: /nginx/Dockerfile
      args:
        NGINX_VERSION: 1.24.0
      cache_from:
        - nginx:latest
    container_name: nginx
    restart: "on-failure"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - steamate-network
  web:
    build:
      context: ./steamate
      dockerfile: /steamate/Dockerfile
      args:
        PYTHON_VERSION: 3.12.9
      cache_from:
        - web:latest
    volumes:
      - ./steamate:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      python manage.py migrate;
      python manage.py load_data;
      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - steamate-network


networks:
  steamate-network:
    driver: bridge

volumes:
  static_volume: