version: '3.8'

services:
  web:
    build:
      context: ./steamate
    volumes:
      - ./steamate:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy 
    command: >
      sh -c "until nc -z db 5432; do
      echo 'Waiting for DB...';
      sleep 2;
      done;
      python manage.py migrate;
      python manage.py runserver 0.0.0.0:8000"
    networks:
      - steamate-network

  db:
    image: ankane/pgvector:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 초기화 스크립트 추가
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      retries: 5
    networks:
      - steamate-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # 개발 환경에서 실행 시 Dockerfile.dev 사용
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    command: npm start
    stdin_open: true
    tty: true
    depends_on:
      - web
    networks:
      - steamate-network


networks:
  steamate-network:
    driver: bridge

volumes:
  db_data: