version: '3.8'

services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy 
    command: >
      sh -c "until nc -z db 5432; do
      echo 'Waiting for DB...';
      sleep 2;
      done;
      python manage.py migrate;
      python manage.py load_data;
      python manage.py runserver 0.0.0.0:8000"

  db:
    image: ankane/pgvector:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 초기화 스크립트 추가
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      retries: 5

volumes:
  db_data: